### ISSUE TITLE
Оплага по QR коду, или аттач к маркету.

### ISSUE THREAD

**Issue by 5x3** [Xposed-Modules-Repo/ru.bluecat.sberbankpatcher#1]
Подскажите, а как починить оплату по QR коду?
Когда захожу в приложение , слева свехру нажимаю значек QR кода и в закладке Сканировать вижу:
--cut--
Пожалуйста, переустановите приложение
Оплата по QR-коду сейчас не работает. Чтобы это исправить, удалите приложние с телефона и скачайте его заново из магазина приложений.
Ваши данные не потеряются, но для входа понадобится номер карты Сбербанка или логин от Сбербанк Онлайн.
Простите за неудобства.
--cut--
Я так понимаю что при установки из apk нет связи (линка) установленного приложения с каким то из маркетов, есть приложения которые этот линк (связь) могут восстановить или "назначить"?
Или может есть другое решение при установке из apk?
Может ли помочь Xposed модуль решить эту проблему если есго (модуль) установить - заработает?
Если есть варианты через adb - или другие методы - прошу сообщить.

Заранее спасибо за помощь.

**Comment by BlueCat300** [comment]
На версии 14.19.0 такое не наблюдается. В будущем используйте telegram группу модуля из описания для других вопросов.
